services:
  cfd:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    image: cfd-gpu
    container_name: cfd
    hostname: cfd
    restart: unless-stopped
    ports:
      - "5000:22"              # SSH
      - "5001-5009:5001-5009"  # 서비스
    volumes:
      - /workspace:/workspace
    deploy:
      resources:
        limits:
          memory: 24g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    image: dev-fullstack
    container_name: dev-fullstack
    hostname: dev-fullstack
    restart: unless-stopped
    ports:
      - "5010:22"              # SSH
      - "5011-5019:5011-5019"  # 서비스
    volumes:
      - /workspace:/workspace
    deploy:
      resources:
        limits:
          memory: 24g
